production:
  app_state: closed
  secret: put_here_your_secret_string
  email_validation: !ruby/regexp /[.@]unito\.it$/

test:
  app_state: open
  no_mail_sending: true
  secret: secret_string
  email_validation: !ruby/regexp /[.@]unito\.it$/

development:
  app_state: open
  no_mail_sending: true
  secret: secret_string
  email_validation: !ruby/regexp /[.@]google\.com$/
