production:
  app_state: closed
  secret: put_here_your_secret_string
  mail_pattern: "/[.@]unito\.it$/"

test:
  app_state: open
  no_mail_sending: true
  secret: secret_string
  mail_pattern: "/[.@]unito\.it$/"

development:
  app_state: open
  no_mail_sending: true
  secret: secret_string
  mail_pattern: "/[.@]unito\.it$/"